float fNewPos;
#define MAX_LINE         168

string STR_TEXT_ENG[MAX_LINE] = {
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Project developers",
"LEOPARD's team",
"Corsairs Ship Pack: OpenSource Edition",
"The founder of the addon",
"LEOPARD",
"",
"Coders",
"LEOPARD",
"Gregg",
"Sinistra",
"BlackThorn",
"Qwerry St.",
"Lipsar",
"Arty",
"Bestreducer",
"annoyer",
"Terra",
"retardokillas",
"DmitrySusokolov",
"",
"Editing and refinement of interfaces",
"LEOPARD",
"Gregg",
"Qwerry St.",
"BlackThorn",
"Lipsar",
"annoyer",
"retardokillas",
"DmitrySusokolov",
"",
"Modeling of ships and locations",
"Noctus",
"Nikk",
"Shanks",
"IG Baron",
"",
"Testing",
"LEOPARD",
"Gregg",
"Googman",
"Qwerry, St.",
"BlackThorn",
"Lipsar",
"Sinistra",
"Arty",
"Bestreducer",
"annoyer",
"Terra",
"Noctus",
"Nikk",
"Shanks",
"IG Baron",
"DmitrySusokolov",
"",
"",
"DH27",
"For his invaluable contribution to community union,", 
"the Corsair website and the largest sponsorship",
"",
"",
"",
"Republishing old modding plugins and improving them",
"for modern Blender programs, as well as many small programs",
"for Blender and many other helpfull programs",
"Arty aka Artes999",
"",
"Creating a launcher for Corsairs Ship Pack",
"DmitrySusokolov",
"",
"When creating the modification, there were",
"the following resources have been used",
"",
"Code and resources from Corsairs: Cursed by Fate",
"",
"Code and resources from Corsairs: To each His Own",
"",
"Code and Resources from Corsairs: A Pirate's Story",
"",
"Resources from Corsairs 2: Pirates of the Caribbean",
"",
"Code and resources from Corsairs: New abilities 0.4.0",
"",
"Code and resources from Gentlemen of Fortune: Eras II",
"",
"Resources from the Corsairs Harbor website",
"",
"Code and resources from 'Reconstruction'",
"",
"",
"Many thanks to the following people",
"whose mods, offers and other novelties",
"officially joined the CSP project",
"Yerilein",
"for his unique character 'The Dark Wanderer' and for helping with the little things",
"Konstrush",
"for his description for the heroes and for the cool HUD",
"Etienne и Narve",
"for the gorgeous characters from Black Sails and more",
"johnny88",
"for the cool HUD and the redesign of all the portraits",
"and also for a bunch of rework on the schedule",
"Kormach",
"for remaking a lot of characters",
"EvgAnat",
"for the gorgeous voice acting of undead bosses and for the unique mechanics",
"Shanks",
"for providing quality of ships and locations",
"MaxTorp",
"for the high quality of character portraits",
"",
"",
"",
"",
"",
"",
"",
"Guys who previously helped on the project",
"Korsar Maxim",
"Zik",
"crem_soda",
"Krah_an_Krait",
"Shaharan aka mimokrokodil",
"",
"",
"Biggest donators",
"MrGray",
"Dangetsu",
"Heli_cat",
"",
"",
"Special thanks to all the developers of the engine",
"OpenSource, as well as our chief navigator",
"kb31",
"Without him, we would hardly have seen the development of the project!",
};

string STR_TEXT[MAX_LINE] = {
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Разработчики проекта",
"LEOPARD's team",
"Corsairs Ship Pack: OpenSource Edition",
"Основатель аддона",
"LEOPARD",
"",
"Кодеры",
"LEOPARD",
"Gregg",
"Sinistra",
"BlackThorn",
"Qwerry, St.",
"Lipsar",
"Arty",
"Bestreducer",
"annoyer",
"Terra",
"retardokillas",
"DmitrySusokolov",
"",
"Правка и доработка интерфейсов",
"LEOPARD",
"Gregg",
"Qwerry, St.",
"BlackThorn",
"Lipsar",
"annoyer",
"retardokillas",
"DmitrySusokolov",
"",
"Моделирование и работа с моделями кораблей и локаций",
"Noctus",
"Nikk",
"Shanks",
"IG Baron",
"",
"Тестирование",
"LEOPARD",
"Gregg",
"Googman",
"Qwerry, St.",
"BlackThorn",
"Lipsar",
"Sinistra",
"Arty",
"Bestreducer",
"annoyer",
"Terra",
"Noctus",
"Nikk",
"Shanks",
"IG Baron",
"DmitrySusokolov",
"",
"",
"DH27",
"За его бесценный вклад в объединение сообщетсва",
"веб сайт на корсарскую тему и самое крупное спонсирование",
"",
"",
"",
"Переиздание старых плагинов для моддинга",
"и их усовершенствование под современные программы",
"для Blender'а, а также многих мелких программ",
"Arty aka Artes999",
"",
"Создание лаунчера для Corsairs Ship Pack",
"DmitrySusokolov",
"",
"При создании модификации были",
"использованы следующие ресурсы",
"",
"Код и ресурсы из 'Корсары: Проклятые Судьбой'",
"",
"Код и ресурсы из 'Корсары: Каждому Свое'",
"",
"Код и ресурсы из 'Корсары: История Пирата'",
"",
"Ресурсы из 'Корсары 2: Пираты Карибского Моря'",
"",
"Код и ресурсы из 'Корсары: New abilities 0.4.0'",
"",
"Код и ресурсы из 'Gentlemen of Fortune: Eras II'",
"",
"Ресурсы с сайта 'Гавань Корсаров'",
"",
"Код и ресурсы из 'Reconstruction'",
"",
"",
"Огромное спасибо следующим людям",
"чьи моды, предложения и прочие новинки",
"официально вошли в проект CSP",
"Ерилейн ",
"За его уникального героя 'Темный Странник'",
"Konstrush",
"За его описание для героев и за интересный HUD",
"Etienne и Narve",
"За шикарных персонажей из Чёрных парусов и не только",
"johnny88",
"За классный худ и доработку всех портретов",
"А также за кучу переделок по графике",
"Kormach",
"За переделку множества персонажей",
"EvgAnat",
"За шикарную озвучку боссов-нежить и за уникальные механики",
"Shanks",
"За предоставление качественных кораблей и локаций",
"MaxTorp",
"За высокое качество портретов персонажей",
"Zendayo",
"За великолепные правки по квестам и за багофиксы",
"ВДД",
"За добавление верёвочек на корабли",
"Nord117",
"За лучшую внимательность к орфографии и грамматике текста",
"",
"Люди, ранее помогавшие по проекту",
"Korsar Maxim",
"Zik",
"crem_soda",
"Krah_an_Krait",
"Shaharan aka mimokrokodil",
"",
"",
"Инвесторы проекта",
"MrGray",
"Dangetsu",
"Heli_cat",
"",
"",
"Особая благодарность всем разработчикам движка",
"OpenSource, а также нашему главному штурману",
"kb31",
"Без него мы вряд ли бы увидели развитие проекта!",
};

string STR_COLOR[MAX_LINE] = {
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"blue",
"violet",
"yellow",
"yellow",
"",
"",
"yellow",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"yellow",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"yellow",
"",
"",
"",
"",
"",
"yellow",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"blue",
"yellow",
"yellow",
"",
"",
"",
"yellow",
"yellow",
"yellow",
"violet",
"",
"yellow",
"violet",
"",
"blue",
"blue",
"",
"yellow",
"",
"yellow",
"",
"yellow",
"",
"yellow",
"",
"yellow",
"",
"yellow",
"",
"yellow",
"",
"yellow",
"",
"",
"blue",
"blue",
"blue",
"yellow",
"",
"yellow",
"",
"yellow",
"",
"yellow",
"",
"",
"yellow",
"",
"yellow",
"",
"yellow",
"",
"yellow",
"",
"yellow",
"",
"yellow",
"",
"yellow",
"",
"",
"yellow",
"",
"",
"",
"",
"",
"",
"",
"blue",
"violet",
"violet",
"",
"",
"yellow",
"yellow",
"violet",
"blue",
};


void InitInterface(string iniName)
{
	GameInterface.title = "";

	SendMessage(&GameInterface, "ls", MSG_INTERFACE_INIT,iniName);

	SetEventHandler("InterfaceBreak", "ProcessCancelExit", 0);
	SetEventHandler("exitCancel", "ProcessCancelExit", 0);
	SetEventHandler("My_MoveText", "MoveText", 0);

	SetFormatedText("INFO_TEXT", "");
	int i, k;

	for(i = 0; i < MAX_LINE; i++)
	{
		if (LanguageGetLanguage() == "russian") {
			SendMessage(&GameInterface, "lsle", MSG_INTERFACE_MSG_TO_NODE, "INFO_TEXT", 0, STR_TEXT[i] + "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
		}
		else {
			SendMessage(&GameInterface, "lsle", MSG_INTERFACE_MSG_TO_NODE, "INFO_TEXT", 0, STR_TEXT_ENG[i] + "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
		}

		if(STR_COLOR[i] != "")
		{
			switch (STR_COLOR[i])
			{
				case "yellow":
					SendMessage(&GameInterface, "lslll", MSG_INTERFACE_MSG_TO_NODE, "INFO_TEXT", 8, i, argb(255,251,237,68));
				break;
				case "red":
					SendMessage(&GameInterface, "lslll", MSG_INTERFACE_MSG_TO_NODE, "INFO_TEXT", 8, i, argb(255,255,162,162));
				break;
				case "blue":
					SendMessage(&GameInterface, "lslll", MSG_INTERFACE_MSG_TO_NODE, "INFO_TEXT", 8, i, argb(255,0,255,255));
				break;
				case "violet":
					SendMessage(&GameInterface, "lslll", MSG_INTERFACE_MSG_TO_NODE, "INFO_TEXT", 8, i, argb(255,255, 20, 147));
				break;
			}
		}
	}

	PostEvent("My_MoveText", 370);
	fNewPos = 0;
	SetMusic("music_Credits"); // LEO: Об авторах - другой музон
}

void ProcessCancelExit()
{
	if(CheckAttribute(&InterfaceStates, "showGameMenuOnExit") && sti(InterfaceStates.showGameMenuOnExit) == true)
	{
		IDoExit(RC_INTERFACE_LAUNCH_GAMEMENU);
		return;
	}

	IDoExit(RC_INTERFACE_OPTIONSCREEN_EXIT);
	if(!CheckAttribute(&InterfaceStates, "InstantExit") || sti(InterfaceStates.InstantExit) == false) ReturnToMainMenu();
}

void IDoExit(int exitCode)
{
 	DelEventHandler("InterfaceBreak","ProcessCancelExit");
	DelEventHandler("exitCancel","ProcessCancelExit");
	DelEventHandler("My_MoveText","MoveText");

	interfaceResultCommand = exitCode;
	if(CheckAttribute(&InterfaceStates,"InstantExit") && sti(InterfaceStates.InstantExit) == true)
		EndCancelInterface(true);
	else
		EndCancelInterface(false);
}

void MoveText()
{
	if(fNewPos >= 1)
	{
		ProcessCancelExit();
	}
	else
	{
		SendMessage(&GameInterface,"lslf",MSG_INTERFACE_MSG_TO_NODE,"INFO_TEXT",2, fNewPos);
		PostEvent("My_MoveText", 20);
		fNewPos = fNewPos + 0.0002;
	}
}
