string DLG_TEXT_BASE[229] = {
"Hello. Let me give you a little advice.",
"I'd love to hear it.",
"I don't need your advice.",
"Greetings. Where are you in a hurry?",
"Just on business.",
"It's none of your business.",
"Good afternoon, how are you?",
"Nothing.",
"I don't have time to talk to you here.",
"Hello. I haven't seen you here before.",
"Yes, I'm just passing through.",
"I don't have time to talk to you here.",
"Greetings. Glad to see you in our area.",
"Hello.",
"I'm sorry, I can't talk to you right now.",
"Hello. Do you want to hear some good advice?",
"Hello. Come on, spit it out.",
"I don't have the slightest desire to waste time.",
"Hello. I have some items that you might be interested in.",
"Let's bargain.",
"I don't have time to talk to you here.",
"Good afternoon. You look tired. For just 200 coins, I can heal your wounds and relieve your fatigue.",
"Give me your drink.",
"I don't believe in miraculous remedies.",
"Hello. I'm in a difficult situation, can you help me?",
"Hmm, why would I...",
"These are your problems, solve them yourself.",
"Would you help a poor sufferer, would you ease his fate with a couple of coins?",
"Of course, the church teaches us to heed the sorrows of our neighbors.",
"Pass by, poor man, and don't you dare come near me anymore.",
"Don't leave a beggar in trouble, give me a coin so that I don't starve to death.",
"What are we talking about, hold 200 coins.",
"Pass by, poor man, and don't you dare come near me.",
"Hello. I see you're armed, surely you often participate in fights?",
"Yes, of course.",
"This is my business. Goodbye.",
"Hello. It's not often you see such a significant person in our wilderness. You must be captain?",
"Yes, how can I help you?",
"You know, I'm in a hurry. Goodbye.",
"Good afternoon. Are you just walking around here, doing nothing?",
"Actually, yes, I can talk to you.",
"No, I have things to do.",
"Listen-don't go into the jungle at night. There are often bandits who attack without warning.",
"Thanks for the advice.",
"If you have problems with the law, then you better not run into a patrol. There are many soldiers here. You'd better get off the island.",
"Interesting.",
"I'm not interested in this kind of advice. Goodbye.",
"But be prepared that the next time you come here, you will be given a cold reception.",
"Okay, I'll take it into account, goodbye.",
"I know the right way to restore your health if something is wrong with you. You can buy a bottle from a seller in the city.",
"Yes, and besides?",
"I don't have time to talk.",
"Well, also, if you rest in the tavern, it will increase your vitality.",
"Thank you.",
"You know, if I suddenly need the latest news or any information, I always go to the tavern keeper. He can answer almost all your questions.",
"Great advice, I'll take it.",
"I see you're a military man. And you have to participate in fights. Remember, take more officers with you. Sometimes it's impossible to survive without their help.",
"Yes, of course.",
"I can see by your bearing that you are captain, no less. If you need a ship, buy it at our shipyard. If suddenly there is not exactly the ship that you wanted to buy, come back in a few days, maybe by this time it will be put up for sale.",
"Good advice, thanks.",
"Sometimes people who have seen a lot in this world appear in these places. You can ask for their help, and they will help you improve your skills in one area or another. I know for sure that their knowledge is almost priceless.",
"Good advice, thanks.",
"If you give me 200 coins, I'll tell everyone what a wonderful person you are. Don't look at me being poor, I have a lot of friends, you will always be welcome here.",
"Throwing money around just so that some poor bastard tells stories about me? Well, no way.",
"Yeah? Well, 200 coins is not such an amount that you don't donate it to someone who needs it so much.",
"Thank you for what you did. I will thank you for this as much as I can. Drink this tincture - it will restore your vitality.",
"Thank you, too.",
"Thank you, I don't have anything to thank you for, at least take this thing, maybe you can benefit from it.",
"I will gladly accept your gift.",
"Thank you, kind man.",
"Don't mention it, goodbye.",
"Captain, take me on board your ship, I have long dreamed of long sea voyages and fierce battles.",
"Of course you will be my officer.",
"No, I don't need rookies.",
"Pay me and I'll show you a couple of techniques to beat anyone in hand-to-hand combat. Or do you want to learn a few defense techniques?",
"I don't need your advice, I already know everything.",
"Show me the defense techniques.",
"I don't need your advice, I already know everything.",
"Show me the attack techniques.",
"Thanks, I don't need anything.",
"I was also a sailor once, a famous navigator. I can tell you a lot about how to handle the crew on the ship.",
"I don't need your advice, I already know everything.",
"Yes, I want to know more about it.",
"Thanks, I don't need anything.",
"I am also a sailor, navigator. For a small fee, I will tell you my secrets that will allow you to better control the ship.",
"I don't need your advice, I already know everything.",
"Yes, I want to know your maneuvering secrets.",
"Thanks, I don't need anything.",
"I am a gunner on a British warship. I will be happy to tell you how to correctly calculate the trajectory of the ball and hit the target every time from the cannon.",
"I don't need your advice, I already know everything.",
"Tell me, I'll pay you as much as you ask.",
"Thanks, I don't need anything.",
"I am a gunner on a British warship. I can tell you a way to quickly reload the guns.",
"I don't need your advice, I already know everything.",
"Tell me, I'll pay you as much as you ask.",
"Thanks, I don't need anything.",
"I am an officer on a British warship. I can tell you many stories about the art of boarding.",
"I don't need your advice, I already know everything.",
"Tell me, I'll pay you as much as you ask.",
"Thanks, I don't need anything.",
"I work at the shipyard and am well versed in the construction and repair of ships. If you pay me, I'll teach your team how to repair the ship quickly.",
"I don't need your advice, I already know everything.",
"Tell me, I'll pay you as much as you ask.",
"Thanks, I don't need anything.",
"I am a merchant, I can teach you such trading techniques that will allow you to increase the profits from your commercial enterprises.",
"I don't need your advice, I already know everything.",
"Tell me, I'll pay you as much as you ask.",
"Thanks, I don't need anything.",
"Well, will you pay me?",
"?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, will you pay me?",
"for the secret techniques of hand-to-hand combat?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, will you pay me?",
"?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, will you pay me?",
"for the secret defense techniques?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, will you pay me?",
"?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, will you pay me?",
"for lessons in human management?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, will you pay me?",
"?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, will you pay me?",
"for advice on ship management?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, will you pay me?",
"?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, will you pay me?",
"for advice on shooting guns?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, will you pay me?",
"?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, will you pay me?",
"for advice on reloading guns?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, will you pay me?",
"?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, will you pay me?",
"for boarding advice?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, what are you going to pay me?",
"?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, will you pay me?",
"for advice on repairing the ship?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, will you pay me?",
"?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Well, will you pay me?",
"for help in trading?",
"I don't seem to have enough money.",
"Yes, I'll pay, tell me.",
"No, it's too much.",
"Thank you for your help, kind man.",
"You're welcome.",
"Well, do you want to buy more elixir?",
"Yes, perhaps more.",
"No, I'm sorry.",
"Well, do you want to bargain?",
"Yes, I want to buy something from you.",
"No, I'm sorry.",
"What do you need? I think we've already discussed everything.",
"It's nothing.",
"What are your orders, Captain?",
"None at all.",
"Do you want to hear some advice?",
"Yes, I'm interested in what you're saying.",
"No, I'm sorry.",
"Listen, lead a righteous life and many people will be glad to see you.",
"Thanks for the advice.",
"I don't advise you to walk here if you have problems with the law. There are many soldiers here. You'd better get off the island.",
"Interesting.",
"I'm not interested in this kind of advice. Goodbye.",
"I know the right way to restore your health if something is wrong with you. You can buy a bottle from a seller in the city.",
"Yes, and besides?",
"I don't have time to talk.",
"You know, if I suddenly need the latest news or any information, I always go to the tavern owner. He can answer almost all your questions.",
"Great advice, I'll take it.",
"I see you're a military man. And you often have to participate in fights. Remember, take more officers with you. Sometimes it's impossible to survive without their help.",
"Yes, of course.",
"I can see by your bearing that you are a captain, no less. If you need a ship, buy it at our shipyard. If suddenly there is not exactly the ship that you wanted to buy, come back in a few days, maybe by this time it will be put up for sale.",
"Good advice, thanks.",
"Sometimes people who have seen a lot in this world appear in these places. You can ask for their help, and they will help you improve your level of knowledge in a particular field. I know for sure - their knowledge is almost priceless.",
"Good advice, thanks.",

};
